server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATASOURCE:jdbc:postgresql://localhost:5432/prova_postgres}
    username: ${POSTGRES_USER:prova_postgres}
    password: ${POSTGRES_PASSWORD:prova_postgres}
    properties:
      schema: public
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  flyway:
    url: ${POSTGRES_DATASOURCE:jdbc:postgresql://localhost:5432/prova_postgres}
    user: ${POSTGRES_USER:prova_postgres}
    password: ${POSTGRES_PASSWORD:prova_postgres}
    schema: public
    default-schema: public
    baseline-on-migrate: true
    check-location: true
    locations: ${FLYWAY_LOCATION:classpath:/db/migration}
    enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
    url: /api-docs
    configUrl: /api-docs/swagger-config
    doc-expansion: none